### ISSUE TITLE
Add --watch

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/split-guide#10]
Right now, to do `watch` via `nodemon`:

```
nodemon --watch ./templates --exec split-guide
```

But it'd be nice to have it built in:

```
split-guide --watch
```

And this would automatically watch the `templates-dir` :+1:

**Comment by sloanelybutsurely** [comment]
👋  I'm happy to take this on. Feel free to assign me and I'll get started either this evening or tomorrow!

**Comment by kentcdodds** [comment]
Thanks @zperrault! I can't assign it to you in the GitHub UI, but you're free to work on it! Thank you!

**Comment by kentcdodds** [comment]
I'll open this up again if I ever feel like implementing it. Or anyone else can implement it if they want.
