### ISSUE TITLE
eslint-disable in examples on README?

### ISSUE THREAD

**Issue by benlesh** [kentcdodds/split-guide#2]
What is the significance of disabling eslint? Do you have some linting setting that doesn't like the comments? I feel like there's something obvious I'm missing.

**Comment by benlesh** [comment]
Specifically I mean the examples like you can find [in the Templates section of the README](https://github.com/kentcdodds/split-guide/blob/bb45defd9685bd5d39534cafd2254de80e6d23d3/README.md#templates)

**Comment by kentcdodds** [comment]
Yeah, actually, that's not needed at all and can be removed. Wanna make a pr?

**Comment by kentcdodds** [comment]
Meh, I'll just do it. Thanks for bringing it up :)

**Comment by benlesh** [comment]
<3 I'm using this for AngularConnect, just FYI.

**Comment by kentcdodds** [comment]
Wonderful! I just used it for Strange Loop and it was fantastic 😻 

One challenge I'm not sure what to do about: people wanting to PR will be tempted to commit to generated files ([for example](https://github.com/kentcdodds/es6-workshop/pull/11)). That project actually has them run a `setup` script which will run the `validate` script which runs the `generate` script. So it's overriding the files anyway... So I'm thinking maybe I'll just not commit the `exercise` and `exercise-final` folders... Thoughts?
