### ISSUE TITLE
(libuv) kqueue(): Too many open files

### ISSUE THREAD

**Issue by benlesh** [kentcdodds/split-guide#3]
If you have a large directory with tons of js under it, you hit some sort of limit with this tool.

Right now I have a `templates` directory underwhich I have an entire `angular-cli`-created app as well as some plain node .js files that I'm templating.

When I run the generator I get the error in the title `(libuv) kqueue(): Too many open files`, and no output directories.

**Comment by benlesh** [comment]
Seems like an easy solution would be to add some sort of either white list of black list to the tool. It's your choice, really. Not sure how you'd like that configured either... in package.json somewhere? or in it's own config file? or perhaps just as a command line argument? The last one seems the least messy and most flexible.

**Comment by kentcdodds** [comment]
Hmmm... So you have files in the `templates` that you want excluded from the final output? Any chance you could just wrap them in:

```
// COMMENT_START
// file contents
// COMMENT_END
```

This would result in the files not being copied. But they would still have to be opened.... Which leads me to my next thing:

We should probably throttle how many files are open at once. [Right now](https://github.com/kentcdodds/split-guide/blob/4a102f44d707869f7862a37d7344184000052468/src/index.js#L42) we just read them all at once. I'm happy to accept a PR to address this. Totally open to suggestions and ideas of the best and cleanest way to do this.

As for the ignoring files, I'd really love to preserve the simplicity of this. If you don't want them in the final output, then delete the files or wrap them in comment directives. Will that work?

**Comment by benlesh** [comment]
I'd like them passed through to the final output, but they're not really templated.

**Comment by benlesh** [comment]
Willing to use a workaround too, I guess.

**Comment by benlesh** [comment]
### WORKAROUND: To those that come after me...

In the short-term my workaround is to have all of my code, including templates in another directory, we'll call it `/src`... I then copy only the files I want to template from `/src` to `/templates` as a step of my script before I run `split-guide generate`.

**Comment by benlesh** [comment]
Longer term, we (I'm volunteering to pair with @kentcdodds on a screencast) can add a feature to support this when we have time.

**Comment by kentcdodds** [comment]
> Longer term, we (I'm volunteering to pair with @kentcdodds on a screencast) can add a feature to support this when we have time.

But don't let that stop anyone who wants to do this first, @blesh and I have lots of other cool things we could pair on :D

**Comment by benlesh** [comment]
> But don't let that stop anyone who wants to do this first, @blesh and I have lots of other cool things we could pair on :D

Yes!

**Comment by raygesualdo** [comment]
@blesh & @kentcdodds Can I take a crack at it?

**Comment by kentcdodds** [comment]
Sure! :D
