### ISSUE TITLE
New feature: CLI options for changing the template & output directories

### ISSUE THREAD

**Issue by janis-kra** [kentcdodds/split-guide#6]
I think it would be awesome if the CLI would offer additional options for changing the directories that split-guide uses (`templates`, `exercises` and `exercises-final`). In my case for example, I want the directory in which the workshop attendees put their code to be `src`. I could create a symlink for this or something like that, but that's not a very clean solution in my opinion.

I would very much like to submit a PR for this within the next few days. Just wanted to ask if this is a feature that you want in your tool before writing the code.

**Comment by kentcdodds** [comment]
Sounds just fine to me! I suggest an API like this: `split-guide generate
--templates-dir other/stuff-for-workshop --exercises-dir src
--exercises-final-dir src-final`

You'll have to figure out how to do that with yargs http://npm.im/yargs.
I don't know how to do it, but I'm sure it's possible :)

I must apologize for the current state of the tests and lack of
documentation for it. I'm using Jest (learn more about that here
http://kcd.im/egghead-webpack), specifically snapshot testing. Make sure
to update and commit the snapshots as part of your PR or the build will

## fail. Thanks!
- Kent C. Dodds https://twitter.com/kentcdodds

**Comment by janis-kra** [comment]
I already looked into yargs, looks doable. As for the testing, I never used
Jest before but wanted to look into it anyway, so that's fine for me, no need
to apologize ;)

**Comment by kentcdodds** [comment]
If you'd like to add to documentation about how to run the tests (even just
linking to the videos I linked to you), that'd be great. Or even creating
_actual_ unit tests would be pretty cool. Right now I'm doing some fancy
stuff by spawning a process to run the binary and then making a snapshot of
the output directory. Pretty fun stuff :)

**Comment by kentcdodds** [comment]
I need this for a workshop I'm doing tomorrow, so I'm going to go ahead and do it right now.

**Comment by janis-kra** [comment]
Sorry, wasn't able to fix the tests so far. Hoping that it will maybe help you, here's how I implemented the CLI options: https://github.com/janis-kra/split-guide/commit/eeedae8817f6c3261d00c2746222e1ffade86576

**Comment by kentcdodds** [comment]
Looks pretty similar to what I have. I'm almost finished :)
